version: '3'
services:
  master:
    image: smartbch/smartbchd:v0.4.4-p1
    container_name: smartbch
    restart: always
    ports:
      - 8545:8545
      - 8546:8546
    ulimits:
      nofile:
        soft: 65535
        hard: 65535
    volumes:
      - /data/smartbchd:/root/.smartbchd
    command:
      start --mainnet-genesis-height=698502