#定义docker compose yml版本
version: "3"
#定义我们的服务对象
services:
  #自定义的服务名称
  nginx:
    #镜像名称，默认拉取本地镜像，没有的话从远程获取
    image: nginx:latest
    #自定义容器的名称
    container_name: c_nginx
    #将宿主机的80端口映射到容器的80端口
    ports:
      - "80:80"
    #将宿主机的 ./www目录和容器的/usr/share/nginx/html目录进行绑定，并设置rw权限
    #将宿主机的 ./nginx/conf/default.conf和容器的/etc/nginx/conf.d/default.conf进行绑定
    volumes:
      - "./www/:/usr/share/nginx/html/:rw"
      - "./nginx/conf/default.conf:/etc/nginx/conf.d/default.conf"
    #设置环境变量，当前的时区
    environment:
      TZ: "Asia/Shanghai"
    #容器是否随docker服务启动重启
    restart: always
    #容器加入名为lnmp的网络
    networks:
      - lnmp
  php:
    image: php:7.3.29-fpm
    container_name: php73
    volumes:
      - "./www/:/var/www/html/:rw"
    restart: always
    cap_add:
      - SYS_PTRACE
    networks:
      - lnmp

  mysql:
    image: mysql:5.6
    container_name: mysql56
    ports:
      - "3306:3306"
    volumes:
      - "./mysql/data:/var/lib/mysql/:rw"
    restart: always
    networks:
      - lnmp
    environment:
      MYSQL_ROOT_PASSWORD: "12345678"
      TZ: "Asia/Shanghai"
    command:
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci
      --bind-address=0.0.0.0
networks:
  #创建了一个自定义的网络叫做lnmp
  lnmp: